[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  IGNORE_FOLDER = "contracts"

[build.environment]
  IGNORE_FOLDER = "contracts"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.lifecycle]
  onBuild = "rm -rf $IGNORE_FOLDER && npm run build"
